# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logrank_instance <- function(groupa, groupb, groupacensored, groupbcensored) {
    .Call(`_fastlogranktest_logrank_instance`, groupa, groupb, groupacensored, groupbcensored)
}

cpu_parallel_logrank1 <- function(groupas_, groupbs_, groupacensoreds_, groupbcensoreds_, threadnumber) {
    .Call(`_fastlogranktest_cpu_parallel_logrank1`, groupas_, groupbs_, groupacensoreds_, groupbcensoreds_, threadnumber)
}

cpu_parallel_logrank <- function(groupas, groupbs, groupacensoreds, groupbcensoreds) {
    .Call(`_fastlogranktest_cpu_parallel_logrank`, groupas, groupbs, groupacensoreds, groupbcensoreds)
}

